spring.application.name=webchat


#logging.level.root=warn

spring.security.user.name=user
spring.security.user.password=user


spring.r2dbc.url=jdbc:mysql://localhost:3306/webchat
spring.r2dbc.username=springstudent
spring.r2dbc.password=springstudent
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto = create



logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

jwt.expiration=3600000
jwt.secret=357638792F423F4428472B4B6250655368566D597133743677397A2443264629